config/routes.rb
Rails.application.routes.draw do
  post 'login' => 'main#login'
  get 'logout' => 'main#logout'
  post 'rsvp' => 'main#rsvp'
  get 'ics' => 'main#ics'
  post 'remind' => 'main#remind'

  # Magic login links:
  get 'invite/:code' => 'main#login'

  # Admin:
  resources :invitations do
    member do
      post 'infiltrate', 'mark_sent'
    end
  end

  root 'main#index'
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  serialize :emails, Array
  serialize :phones, Array
  serialize :guests, Array
  serialize :tags, Array

  validates :rsvp, inclusion: { in: %w[yes no maybe], allow_nil: true }
  validates :code, uniqueness: true, exclusion: { in: %w[melon mellon hocuspocus abracadabra alakazam opensesame hunter2 friend enter friendandenter getlamp] }

  before_save :standardise_phone_numbers

  # Tags which have meaning, so far:
  KNOWN_TAGS = {
    'admin' => "Can manage the party, invitations, etc. Don't give this out willy-nilly.",
    'local' => "Don't show the 'wide area' map. Discourage travel by car.",
    'friend of annabel' => 'Substitutes the intro message to one that introduces the hosts as "Annabel and her family".',
    'friend of john' => 'Substitutes the intro message to one that introduces the hosts as "John and his family".',
    'camping' => 'Invitee has indicated that they intend to camp. [self-managed]',
    'public_transport' => 'Invitee has indicated that they intend to travel using public transport [self-managed]',
    'invitation_sent' => 'Invitation has been sent. Help keep track of who we\'ve send a message to already!',
    '3r' => "They're a Three Ringer! [Auto-Friends Group]",
    'abnib' => "They're an Abnib person! [Auto-Friends Group]",
    'resident' => "Some or all of them usually live at The Green!",
    'attended_2022' => 'Did they come last year?',
    'bodleian' => "Dan's dream team: the Old Guard of Cake and Magic. [Auto-Friends Group]",
    'anonymous_invitation' => "We've pre-generated a stack of magic words for use on paper, \"write in a name and hand them out\" invitations. So as not to clutter the UI, these are usually invisible in the admin interface until somebody logs into them. You probably don't want to tick this box.",
  }

  def tagged?(tag)
    (tags || []).include?(tag)
  end

  def standardise_phone_numbers
    (self.phones ||= []).map!{|p| Invitation::standardise_phone_number(p) }
  end

  def emails_list
    (self.emails || []).join("\n")
  end

  def emails_list=(new_emails)
    self.emails = new_emails.split("\n").map(&:strip).reject(&:blank?)
  end

  def phones_list
    (self.phones || []).join("\n")
  end

  def phones_list=(new_phones)
    self.phones = new_phones.split("\n").map(&:strip).reject(&:blank?)
  end

  def guests_json
    (self.guests || []).to_json
  end

  def guests_json=(new_json)
    self.guests = JSON.parse(new_json)
  end

  def guests_editable_text
    (self.guests || []).map{|g|
      suffixes = []
      suffixes << ':c' if g[:child]
      suffixes << ':v' if g[:vegetarian]
      "#{g[:name]}#{suffixes.join('')}"
    }.join("\n")
  end

  def guests_editable_text=(new_text)
    self.guests = new_text.split("\n").map(&:strip).reject(&:blank?).map{|g|
      guest = { child: false, vegetarian: false }
      while g =~ /^(.+):([cv])$/
        guest[:child] = true if $2 == 'c'
        guest[:vegetarian] = true if $2 == 'v'
        g = $1
      end
      guest[:name] = g
      guest
    }
  end

  def self.standardise_phone_number(phone)
    phone.gsub(/[^0-9]/, '')
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :admin_only
  before_action :set_invitation, only: %i[show edit update destroy infiltrate mark_sent]

  # GET /invitations or /invitations.json
  def index
    @invitations = Invitation.order(Arel.sql("IF(rsvp = 'yes', 0, 1), IF(rsvp = 'maybe', 0, 1), IF(rsvp = 'no', 0, 1), IF(name = '', 1, 0), name")).all.to_a
    @invitations.reject!{|i|!i.last_login && i.tagged?('anonymous_invitation')} unless params[:show_anonymous]
  end

  # GET /invitations/1 or /invitations/1.json
  def show
  end

  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end

  # GET /invitations/1/edit
  def edit
  end

  def mark_sent
    @invitation.tags ||= []
    @invitation.tags << 'invitation_sent'
    @invitation.save
    flash[:notice] = "Marked-as-sent invitation to #{@invitation.name}"
    redirect_to "/invitations#invitation-#{@invitation.id}"
  end

  # POST /invitations or /invitations.json
  def create
    @invitation = Invitation.new(invitation_params)

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to "/invitations#invitation-#{@invitation.id}", notice: "Invitation was successfully created." }
        format.json { render :show, status: :created, location: @invitation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invitations/1 or /invitations/1.json
  def update
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to "/invitations#invitation-#{@invitation.id}", notice: "Invitation was successfully updated." }
        format.json { render :show, status: :ok, location: @invitation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1 or /invitations/1.json
  def destroy
    @invitation.destroy

    respond_to do |format|
      format.html { redirect_to invitations_url, notice: "Invitation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def infiltrate
    session[:infiltrating_from] = @admin.id
    cookies.encrypted.permanent[:invitation] = @invitation.id
    redirect_to root_url
  end

  private
    def admin_only
      @admin = Invitation.find_by(id: cookies.encrypted.permanent[:invitation])
      redirect_to(root_url) unless @admin.tagged? 'admin'
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      @invitation = Invitation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invitation_params
      parsed_params = params.require(:invitation).permit(:name, :notes, :private_notes, :code, :last_login, :emails_list, :phones_list, :tags, :guests_editable_text)
      parsed_params[:tags] = params[:invitation][:tags] # manual hack: shouldn't be needed but is? can't be bothered working out why...
      parsed_params
    end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_with(model: invitation, class: 'edit-invitation-form') do |form| %>
  <% if invitation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
        <% invitation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :notes, 'Notes (visible to invitee)', style: "display: block" %>
    <%= form.text_area :notes %>
  </div>

  <div>
    <%= form.label :private_notes, 'Private notes (for Q-T-A only!)', style: "display: block" %>
    <%= form.text_area :private_notes %>
  </div>

  <div>
    <%= form.label :code, 'Magic Word (lowercase letters and numbers only; you might be able to get away with hyphens I suppose)', style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :emails_list, 'Email addresses (one per line, can be used to recover magic word)', style: "display: block" %>
    <%= form.text_area :emails_list %>
  </div>

  <div>
    <%= form.label :phones_list, 'Mobile numbers (one per line, can be used to recover magic word)', style: "display: block" %>
    <%= form.text_area :phones_list %>
  </div>

  <div>
    <p>Tags:</p>
    <ul>
      <% Invitation::KNOWN_TAGS.sort.each do |tag, description| %>
        <li class="edit-invitation-form-tag-<%= tag.underscore %>">
          <label>
            <%= form.check_box :tags, {multiple: true}, tag, nil %>
            <strong><%= tag %></strong><br>
            <small><%= description %></small>
          </label>
        </li>
      <% end %>
    </ul>
  </div>

  <div>
    <%= form.label :guests_editable_text, "Guests (one per line, use suffixes like ':c' for child and ':v' for vegetarian, chain multiple with colons e.g. ':c:v')", style: "display: block" %>
    <%= form.text_area :guests_editable_text %>
  </div>

  <div>
    <%= form.submit %> <%= link_to 'Back', invitations_path, class: 'btn' %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing invitation</h1>

<%= render "form", invitation: @invitation %>

app/views/invitations/index.html.erb
<h1>Invitations</h1>

<p style="text-align: center;">
  <%= link_to 'Add invitation', new_invitation_path, class: 'btn' %>
  <%= link_to 'Back to My Invitation', root_url, class: 'btn' %>
</p>

<div id="filters"></div>

<table id="all-invitations">
  <thead>
    <tr>
      <th>Name</th>
      <th>Sent?</th>
      <th>RSVP</th>
      <th>Problems?</th>
      <th>Tags</th>
      <th>Last Login</th>
      <th>Adults</th>
      <th>Children</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @invitations.each do |invitation| %>
      <tr class="shown rsvp-<%= invitation.rsvp || 'unanswered' %> <%= invitation.tagged?('invitation_sent') ? 'f-sent' : 'f-unsent' %>" id="invitation-<%= invitation.id %>">
        <td>
          <% if invitation.name.blank? # anonvitation %>
            🕵️ <code><%= invitation.code %></code>
          <% else %>
            <%= invitation.name %>
          <% end %>
        </td>
        <td style="text-align: center;">
          <%= invitation.tagged?('invitation_sent') ? '📨' : '📤' %>
        </td>
        <td style="text-align: center;">
          <%= (invitation.rsvp == 'yes') ? '✅' : (invitation.rsvp == 'no' ? '❌' : (invitation.rsvp == 'maybe' ? '❓' : '')) %>
        </td>
        <td>
          <%= '📱 no contact!<br>'.html_safe if ((invitation.phones || []) + (invitation.emails || [])).empty? %>
          <%= '😅 rsvp yes, no guests!<br>'.html_safe if invitation.guests.empty? && (invitation.rsvp == 'yes') %>
          <%= '🪄 no magic word!<br>'.html_safe if invitation.code.blank? %>
        </td>
        <td>
          <%= (invitation.tags || []).join('<br>').html_safe %>
        </td>
        <td>
          <%= invitation.last_login.try(:to_date) %>
        </td>
        <td>
          <%=
            adults = (invitation.guests || []).reject{|g|g[:name].blank?}.select{|g|!g[:child]}.count
            @total_adults ||= 0
            @total_confirmed_adults ||= 0
            (@total_adults += adults) if invitation.rsvp != 'no'
            (@total_confirmed_adults += adults) if invitation.rsvp == 'yes'
            adults
          %>
        </td>
        <td>
          <%=
            children = (invitation.guests || []).reject{|g|g[:name].blank?}.select{|g|g[:child]}.count
            @total_children ||= 0
            @total_confirmed_children ||= 0
            (@total_children += children) if invitation.rsvp != 'no'
            (@total_confirmed_children += children) if invitation.rsvp == 'yes'
            children
          %>
        </td>
        <td>
          <div style="display: flex;">
            <%= link_to 'Edit', edit_invitation_path(invitation), class: 'btn btn-sm' %>
            <%= button_to 'Infiltrate', infiltrate_invitation_path(invitation), class: 'btn btn-sm' %>
            <%= link_to 'Invite', invitation, class: 'btn btn-sm' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td style="text-align: right; font-weight: bold;">Total (range):</td>
      <td><%= @total_confirmed_adults %> &mdash; <%= @total_adults %></td>
      <td><%= @total_confirmed_children %> &mdash; <%= @total_children %></td>
      <td><%= @total_confirmed_adults + @total_confirmed_children %> &mdash; <%= @total_adults + @total_children %></td>
    </tr>
  </tfoot>
</table>

<script type="text/javascript">
  const invitationsTable = document.querySelector('#all-invitations tbody');
  const filters = document.getElementById('filters');
  const filterData = [
    'Sent',
    { class: 'f-sent', label: '📨 Sent' },
    { class: 'f-unsent', label: '📤 Unsent' },
    '<br><br>RSVP',
    { class: 'rsvp-yes', label: '✅ Yes' },
    { class: 'rsvp-no', label: '❌ No' },
    { class: 'rsvp-maybe', label: '❓ Maybe' },
    { class: 'rsvp-unanswered', label: 'Unanswered' },
  ];
  const filterList = filterData.map(f=> (typeof f === 'string') ? `<strong>${f}:</strong>` :  `<label><input type="checkbox" class="filter-box" data-filter="${f.class}" checked> ${f.label}</label>`);
  filters.innerHTML = `<p>${filterList.join(' ')}</p>`;
  filters.addEventListener('change', ()=>{
    [...invitationsTable.querySelectorAll('tr')].forEach(tr=>tr.classList.add('shown'));
    [...filters.querySelectorAll('input[type="checkbox"]:not(:checked)')].forEach(checkbox=>{
      [...invitationsTable.querySelectorAll(`tr.${checkbox.dataset.filter}`)].forEach(tr=>tr.classList.remove('shown'));
    });
  });
</script>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render "form", invitation: @invitation %>

app/views/invitations/show.html.erb
<h1>Inviting <%= @invitation.name %></h1>

<% if @invitation.tagged? 'invitation_sent' %>
  <p>
    <strong>This person's already been sent an invitation!</strong> Take care not to harass them too much!
  </p>
<% end %>

<h2>Sample Email</h2>
<p>
  <% if @invitation.emails.empty? %>
    If you know their email address, why didn't you <%= link_to 'put it on the form', edit_invitation_path(@invitation) %>!?
  <% else %>
    Perhaps send this to: <code><%= @invitation.emails.join(',') %></code>
  <% end %>
</p>
<blockquote>
  <p>
    Dear <%= @invitation.name %>,
  </p>
  <p>
    Following the success of last year's event, we're throwing another
    <a href="https://qta23.uk/invite/<%= @invitation.code %>"><strong>Summer Party at The Green</strong></a>
    this year.
  </p>
  <p>
    We hope you'll come and join us on Saturday 19 August 2023 at
    <a href="https://thegreen.q-t-a.uk/">The Green in Sutton</a>.
  </p>
  <p>
    For more details and to RSVP, visit <a href="https://qta23.uk/invite/<%= @invitation.code %>">qta23.uk</a>
    and log in with the magic word: <code><%= @invitation.code %></code>
  </p>
  <p>
    Hope to see you there!
  </p>
  <hr>
  <p>
    Dan, Ruth, JTA, and the rest of the family
  </p>
</blockquote>

<h2>Sample WhatsApp</h2>
<p>
  <% if @invitation.phones.empty? %>
    If you know their phone number, why didn't you <%= link_to 'put it on the form', edit_invitation_path(@invitation) %>!?
  <% else %>
    Perhaps send this to:
    <%= @invitation.phones.map{|phone| link_to(phone, "https://wa.me/#{phone.gsub(/^0/, '44')}") }.to_sentence.html_safe %>
  <% end %>
</p>
<blockquote>
  <p>
    <%= @invitation.name %>,
    <br><br>
    Following the success of last year's event, we're throwing another
    *<strong>Summer Party at The Green</strong>*
    this year.
    <br><br>
    We hope you'll come and join us on Saturday 19 August 2023 at The Green, Eynsham Road, Sutton, OX29 5RZ.
    <br><br>
    For more details and to RSVP, visit https://qta23.uk and log in with the magic word: ```<code><%= @invitation.code %></code>```
    <br><br>
    Or log in using this magic link: https://qta23.uk/invite/<%= @invitation.code %>
    <br><br>
    Hope to see you there!
  </p>
</blockquote>

<p>
  <% unless @invitation.tagged? 'invitation_sent' %>
    <%= button_to 'Mark invitation as sent', mark_sent_invitation_path(@invitation), class: 'btn' %>
  <% end %>
  <%= link_to 'Back to list', invitations_path, class: 'btn' %>
</p>